# This file may be used to create an environment using:
# $ conda env create --name <env> --file <this file>
# platform: osx-64
name: nupic.research
channels:
  - defaults
  - pytorch
  - nvidia
  - conda-forge

# Uncomment these lines to force x86 on Apple M1 laptops
# variables:
#   CONDA_SUBDIR: osx-64

dependencies:
  - python=3.8
  - pip

  - pip:
      # Install nupic.torch libraries in develop mode.
      # Assume libraries were cloned into ${HOME}/nta folder
      - -e ../nupic.torch

      # Install nupic.research and its dependencies 
      - -r requirements.txt
